volumes:
  whatsfeed_mariadb:
  testing_whatsfeed_mariadb:
services:
  db:
    image: mariadb:11
    container_name: whatsfeed_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: y/D}=?ERlnL%DI:A5L
    volumes:
      - whatsfeed_mariadb:/var/lib/mysql
      - ./mariadb:/docker-entrypoint-initdb.d
    restart: always
    networks:
      whatsfeed_network:
  web:
    restart: on-failure
    build: ./web
    hostname: node_wa_scraper   
    ports: 
      - "81:5000"
    volumes:
      - ./web/src:/usr/src/app/src
      - ./profile_pictures:/usr/src/app/images
    networks:
      - whatsfeed_network
    depends_on:
      - db
  api:
    build:
      context: whatsfeed_app
      dockerfile: Dockerfile
    stop_signal: SIGINT
    # to sync the ./api dir with the container only for development
    volumes:
      - ./whatsfeed_app/app:/usr/src/app/app

    environment:
        #so manage.py knows which app to run
      - FLASK_APP=whatsfeed.py
      - PRODUCTION_DATABASE_URI=${PRODUCTION_DATABASE_URI}
      - APP_SETTINGS=config.ProductionConfig
    healthcheck:
      test: curl --fail http://localhost:5000 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
    networks:
      whatsfeed_network:
        aliases:
          - whatsfeed_app
    restart: unless-stopped
    depends_on:
      - db
      - web 
  
  nginx:
    build: whatsfeed_app/nginx
    ports:
      - 5006:80
    volumes:
      - ${PICTURES_DIR}:/var/www/html/images
    depends_on:
      - api
    networks:
      whatsfeed_network:
    restart: always

networks:
  whatsfeed_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/24
