volumes:
  whatsfeed_mariadb:
  testing_whatsfeed_mariadb:
services:
  db:
    image: mariadb:11
    container_name: whatsfeed_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: y/D}=?ERlnL%DI:A5L
    volumes:
      - whatsfeed_mariadb:/var/lib/mysql
      - ./mariadb:/docker-entrypoint-initdb.d
    restart: always
    networks:
      whatsfeed_network:
        ipv4_address: 172.24.0.2
  web:
    restart: on-failure
    build: ./web
    hostname: node_wa_scraper   
    ports: 
      - "81:5000"
    volumes:
      - ./web/src:/usr/src/app/src
    networks:
      - whatsfeed_network
    environment:
      - DEBUG=prisma*
  

networks:
  whatsfeed_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/24
