version: '3'
volumes:
  whatsfeed_mariadb:
services:
  db:
    image: mariadb:11
    container_name: whatsfeed_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: y/D}=?ERlnL%DI:A5L
    volumes:
      - whatsfeed_mariadb:/var/lib/mysql
      - ./mariadb:/docker-entrypoint-initdb.d
