version: '3.8'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    stop_signal: SIGINT
    # to sync the ./api dir with the container only for development
    volumes:
      - ./api:/usr/src/app/api
    ports:
      - 5004:5000
    environment:
        #so manage.py knows which app to run
      - FLASK_APP=api/__init__.py
      - PRODUCTION_DATABASE_URI=${PRODUCTION_DATABASE_URI}
      - APP_SETTINGS=api.config.ProductionConfig
      # - APP_SETTINGS=api.config.TestingConfig
      # - APP_SETTINGS=api.config.DevelopmentConfig
    healthcheck:
      test: curl --fail http://localhost:5000 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
    networks:
      whatsappweb_scraper_whatsfeed_network:
        ipv4_address: 172.24.0.3
        aliases:
          - api

networks:
  whatsappweb_scraper_whatsfeed_network:
    external: true